In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],columns=['A','B','C'], index=['a','b','c','d'])

In [4]:
df.head()

    A   B   C
a   1   2   3
b   4   5   6
c   7   8   9
d  10  11  12

In [5]:
df.tail(2)

    A   B   C
c   7   8   9
d  10  11  12

In [6]:
df.columns

Index(['A', 'B', 'C'], dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, a to d
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
dtypes: int64(3)
memory usage: 300.0+ bytes

In [9]:
df.describe()

               A          B          C
count   4.000000   4.000000   4.000000
mean    5.500000   6.500000   7.500000
std     3.872983   3.872983   3.872983
min     1.000000   2.000000   3.000000
25%     3.250000   4.250000   5.250000
50%     5.500000   6.500000   7.500000
75%     7.750000   8.750000   9.750000
max    10.000000  11.000000  12.000000

In [13]:
df['A'].unique()

array([ 1,  4,  7, 10])

In [14]:
df.shape

(4, 3)

In [16]:
df.size

12

In [17]:
df.loc['a']

A    1
B    2
C    3
Name: a, dtype: int64

In [18]:
df.loc[['a','d']]

    A   B   C
a   1   2   3
d  10  11  12

In [23]:
df.iloc[:,[0,1,2]]

    A   B   C
a   1   2   3
b   4   5   6
c   7   8   9
d  10  11  12

In [26]:
df.sort_values(["A"])

    A   B   C
a   1   2   3
b   4   5   6
c   7   8   9
d  10  11  12

In [27]:
df.sort_values(["A"], ascending=False)

    A   B   C
d  10  11  12
c   7   8   9
b   4   5   6
a   1   2   3

In [29]:
df.sort_values(by='A')

    A   B   C
a   1   2   3
b   4   5   6
c   7   8   9
d  10  11  12

In [30]:
df.loc[df["A"]>3]

    A   B   C
b   4   5   6
c   7   8   9
d  10  11  12

In [31]:
df.query('A>3')

    A   B   C
b   4   5   6
c   7   8   9
d  10  11  12

In [33]:
df.drop(columns=['A'])

    B   C
a   2   3
b   5   6
c   8   9
d  11  12

In [35]:
df['A']=df['B']*df['C']

In [36]:
df

     A   B   C
a    6   2   3
b   30   5   6
c   72   8   9
d  132  11  12

In [37]:
df.rename(columns={'A':'B_C'}, inplace=True)

In [38]:
df

   B_C   B   C
a    6   2   3
b   30   5   6
c   72   8   9
d  132  11  12